# Generated by Django 4.1.1 on 2022-09-29 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('talla', models.CharField(max_length=10)),
                ('imagen', models.ImageField(upload_to='productos')),
                ('icono', models.ImageField(upload_to='iconos')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('carrito', 'carrito'), ('cancelado', 'cancelado'), ('comprado', 'comprado')], default='carrito', max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProductos.producto')),
            ],
            options={
                'verbose_name_plural': 'Mi Carrito',
            },
        ),
    ]
